### ISSUE TITLE
persist environment variables in global shell config

### ISSUE THREAD

**Issue by rokroskar** [rocker-org/devcontainer-features#168]
The environment variables are currently set using the `containerEnv` option of the feature spec: 

https://github.com/rocker-org/devcontainer-features/blob/1e2af2ddd61338770445762090791511fa566fbc/src/miniforge/devcontainer-feature.json#L31-L34

This works if this feature is referenced directly in the devcontainer spec, however if it is installed indirectly through another feature, the environment variables do not propagate to the final `Dockerfile`. For example, it's common for features to use other features like this in their `install.sh` script:

```shell
nanolayer \
    install \
    devcontainer-feature \
    "ghcr.io/rocker-org/devcontainer-features/miniforge:1"
```

Perhaps the conda environment variables (`CONDA_DIR`, `CONDA_SCRIPT`) and the modification to the `PATH` (adding `/opt/conda/bin`) should be added to the bashrc [here](https://github.com/rocker-org/devcontainer-features/blob/1e2af2ddd61338770445762090791511fa566fbc/src/miniforge/install.sh#L148-L152) or even to `/etc/bash.bashrc`? For example, see [here](https://github.com/devcontainers-contrib/features/blob/main/src/pipx-package/install.sh#L27-L40) to see how the `pipx` feature handles this. I assume it's exactly for the reason I mention at the top, because it's often used as a way to distribute other packages as features.

**Comment by eitsupi** [comment]
Thanks for opening this issue.

But I do not know if we should address that issue here.

- We do not know if bash is used in the container.
- Why doesn't nanolayer adhere to the Dev Container Spec? Making invasive changes in consideration of tools that do not follow the Dev Container Spec is not a good idea to me.
- The purpose of `ghcr.io/rocker-org/devcontainer-features/miniforge` is to provide an alternative to [`ghcr.io/devcontainers/features/conda`](https://github.com/devcontainers/features/tree/main/src/conda). So can we discuss whether we should make these changes in <https://github.com/devcontainers/features> first?

I hope this answer is acceptable to you.

**Comment by rokroskar** [comment]
Yes I don't disagree with you. I think there is an inconsistency with how the devcontainer tooling handles this case. For example, if I run such an extension in vscode the `PATH` is set correctly, but that's because the vscode devcontainer tooling makes additional changes to the container (it introspects the features and adjusts the `PATH`). In my view, this is an inconsistency because it _requires_ that you run the dev container with the devcontainer tooling. 

`nanolayer` is actually a tool distributed for use in dev containers, so it does adhere to the spec. 

I suppose the solution would be for the devcontainer build phase to do the same environment reconciliation that now happens at runtime, but that's a deeper change. I'll open an issue in https://github.com/devcontainers/cli.

**Comment by rokroskar** [comment]
This problem is solved by https://github.com/devcontainers/cli/pull/530
